"""Alter user_id to String type for UUID

Revision ID: 0a20a4b4f3f6
Revises: 7210bc0382a1
Create Date: 2024-11-08 14:58:30.295922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a20a4b4f3f6'
down_revision: Union[str, None] = '7210bc0382a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
