"""Removing Master Color

Revision ID: 552e97dba1b5
Revises: 8fae29156611
Create Date: 2024-11-09 20:21:05.250008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '552e97dba1b5'
down_revision: Union[str, None] = '8fae29156611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_colors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diver_gears', sa.Column('master_color_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('diver_gears_ibfk_2', 'diver_gears', 'master_colors', ['master_color_id'], ['id'])
    op.drop_column('diver_gears', 'color')
    op.create_table('master_colors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('hex_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('modified_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_master_colors_id', 'master_colors', ['id'], unique=False)
    # ### end Alembic commands ###
