"""Fixing and Adding Master Brands

Revision ID: 66104d5ef136
Revises: 0a20a4b4f3f6
Create Date: 2024-11-09 20:00:12.386682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66104d5ef136'
down_revision: Union[str, None] = '0a20a4b4f3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
