"""Fixing and Adding Master Brands

Revision ID: 76abaf05155c
Revises: 66104d5ef136
Create Date: 2024-11-09 20:01:49.100462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76abaf05155c'
down_revision: Union[str, None] = '66104d5ef136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
