"""Add created_at and modified_at columns

Revision ID: 7a794b5d12da
Revises: 6279d3e01c3d
Create Date: 2024-10-28 17:39:17.732497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a794b5d12da'
down_revision: Union[str, None] = '6279d3e01c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('profile_love_tos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('profile_love_tos', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('profile_previous_dive_sites', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('profile_previous_dive_sites', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_previous_dive_sites', 'modified_at')
    op.drop_column('profile_previous_dive_sites', 'created_at')
    op.drop_column('profile_love_tos', 'modified_at')
    op.drop_column('profile_love_tos', 'created_at')
    op.drop_column('onboarding_profiles', 'modified_at')
    op.drop_column('onboarding_profiles', 'created_at')
    # ### end Alembic commands ###
