"""Fixing Master Brands

Revision ID: a9156a0a6b8d
Revises: 76abaf05155c
Create Date: 2024-11-09 20:04:55.925888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9156a0a6b8d'
down_revision: Union[str, None] = '76abaf05155c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
