"""Add unique constraint to user_id in onboarding_profiles

Revision ID: b624977f92f1
Revises: 7a794b5d12da
Create Date: 2024-10-29 07:44:36.755616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b624977f92f1'
down_revision: Union[str, None] = '7a794b5d12da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_onboarding_profiles_user_id', 'onboarding_profiles', ['user_id'])
    op.create_unique_constraint(None, 'onboarding_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboarding_profiles', type_='unique')
    op.drop_constraint('uq_onboarding_profiles_user_id', 'onboarding_profiles', type_='unique')
    # ### end Alembic commands ###
