"""Alter user_id to String type for UUID

Revision ID: ea277f74be62
Revises: 29609bd8f2d8
Create Date: 2024-11-08 14:51:35.908150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea277f74be62'
down_revision: Union[str, None] = '29609bd8f2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diver_profiles', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               nullable=True)
    op.create_index(op.f('ix_diver_profiles_user_id'), 'diver_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diver_profiles_user_id'), table_name='diver_profiles')
    op.alter_column('diver_profiles', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
